### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by ruyanve** [ruyanve/Derivation#2]
- [ ] clean up all textures
- [ ] new stone textures
- [ ] dark oak planks
- [x] fix/add random textures
- [x] fix/add connected textures
- [ ] 3D models
- [ ] fix ctm Ores (they look horrible!)
